### ISSUE TITLE
Page227中，第12章，luaTable结构体改变不对

### ISSUE THREAD

**Issue by zedongh** [zxh0/luago-book#12]
书上描述`luaTable`只增加`keys`字段, 但是下面的描述`nextKey`方法提到了`changed`字段, 我看ch12的源码中为next增加
```go
keys      map[LuaValue]LuaValue
lastKey   LuaValue
changed   bool
```

**Comment by zxh0** [comment]
你好，非常感谢，这里确实是有问题。是这样的：第12章源代码里，luaTable的确增加了三个字段，`keys`、`lastKey`、`changed`；不过为了便于文字叙述，我本意是想在不影响主要逻辑的前提下，把不太重要的`lastKey`和`changed`这两个字段隐去。不过我在处理代码时疏忽了，本来应该去掉`nextKey()`函数里改变`changed`状态的那行代码，但是没有去掉。这样就给读者阅读带来了不便，非常抱歉。

**Comment by zxh0** [comment]
我会把这个问题登记到勘误表里，下次印刷时，会把`self.changed = false`这行代码去掉。谢谢。

**Comment by zxh0** [comment]
@zedongh 已经登记
https://github.com/zxh0/luago-book/blob/master/errata.md
