### ISSUE TITLE
Page109, TEST 指令的讲解

### ISSUE THREAD

**Issue by BalusChen** [zxh0/luago-book#15]
P109，关于`TEST`指令，书上是这样讲的:

> 判断寄存器 A（索引由操作数 A 指定）中的值转换为布尔值之后是否和操作数 C 表示的布尔值一致，如果一致，则跳过下一条指令。

但是根据`TEST`指令的伪码:

``` lua
if not (R(A) <=> C) then pc++
```

可以发现其实应该是“如果不一致，则跳过下一条指令”。

**Comment by zxh0** [comment]
已经登记到勘误表，会在下次印刷时修正，非常感谢 ：）
