### ISSUE TITLE
Page127 GetTable方法的讲解

### ISSUE THREAD

**Issue by BalusChen** [zxh0/luago-book#17]
P127处，`GetTable`方法中用到了`getTable`方法：

> 为了减少重复，我们把根据键从表里取值的逻辑抽取成`GetTable()`方法，代码如下所示。

但是下面展示的却是`getTable()`方法的代码，而且根据上下文可知，应该是”抽取成`getTable()`方法。“

同理，P129中介绍`SetTable`方法时也出现了类似的错误。

**Comment by zxh0** [comment]
已经登记，感谢 😊
