### ISSUE TITLE
改错和其他

### ISSUE THREAD

**Issue by CaigerDeng** [zxh0/luago-book#19]
感谢作者写了这本书！以下是我在阅读的时候遇到的一些错误：
页数 | 章节 |  位置 | 原文 | 更正
-|-|-|-|-
124 | 7.2 | 倒数一段话第一行| 由于set()方法…… | 由于put(...)方法……
178 | 9.3.2 | 倒数第一段话最后一行| 录下创建inst_Upvalue.go文件 | 录下创建inst_upvalue.go文件
187 | 10.1.2 | 第一段话第一行| 我们再用“luc -l -l”分析…… | 我们再用“luac -l -l”分析……
192 | 10.2.2 | 倒数第二段话倒数第三行| 读者打开luaStack.go文件…… | 读者打开lua_stack.go文件……
227 | 12.2.1 | 第一段话第一行| 请读者打开luaTable.go文件…… | 请读者打开lua_table.go文件……
228 | 12.2.2 | 倒数第一段话第二行| （和luaTable.go文件…… | （和lua_table.go文件……
372 | 19.3 | 倒数第一段话第二行| 就可以通过面相对象…… | 就可以通过面向对象……
373 | 19.3 | 第二句代码的打印结果| print(s:len())   --> 2 | print(s:len())   --> 3

另外，Windows和Mac的命令行略有不同，而这本书上是Mac版命令行，我开了[一个库](https://github.com/CaigerDeng/WriteYourOwnLua_Win_CMD)记录本书Windows版命令行内容，不关心命令行差异的用Windows的读者可以从这库里直接拷贝命令行内容。

**Comment by zxh0** [comment]
@CaigerDeng 非常感谢，我检查了一遍，上面的问题的确都是存在的，我把它们合并到勘误表里了。👍
