### ISSUE TITLE
9.3.2节的 getTabUp最后不应该vm.Pop(1)

### ISSUE THREAD

**Issue by King19931229** [zxh0/luago-book#23]
vm.PushGlobalTable()  +1
vm.GetRK(c) +1
vm.GetTable(-2) +0
vm.Repace(a) -1
vm.Pop(1)  -1

如果执行了vm.Pop(1)会把加载进栈的Go函数清除，相当于调用getTabUp后没有起到任何作用

**Comment by zxh0** [comment]
感谢反馈，还是希望能写一个最小化的Lua脚本，重现问题。

**Comment by King19931229** [comment]
> 感谢反馈，还是希望能写一个最小化的Lua脚本，重现问题。

测试代码：
print("hello world")

字节码：
main <hello.lua:0,0> (4 instructions at 003e8670)
0+ params, 2 slots, 1 upvalue, 0 locals, 2 constants, 0 functions
        1       [28]    GETTABUP        0 0 -1  ; _ENV "print"
        2       [28]    LOADK           1 -2    ; "hello world"
        3       [28]    CALL            0 2 1
        4       [28]    RETURN          0 1

这里可以看到
GETTABUP        0 0 -1    把print函数放到栈上索引0的位置
LOADK             1 -2       把"hello world"放到栈上索引1的位置
CALL                0 2 1      调用索引0上的print函数

下面是9.3.2实现的GETTABUP代码 右侧+ -表示栈元素的增长
vm.PushGlobalTable() +1
vm.GetRK(c) +1
vm.GetTable(-2) +0（把key从栈顶弹出 把value弹入）
vm.Repace(a) -1
vm.Pop(1) -1

可以看到栈元素没有增长，原因是最后vm.Pop(1)把print给Pop出来了，top还是0
在第10章里的解释是GETTABUP是修改栈元素的
所以疑问是GETTABUP包括LOADK是否应该修改栈的top呢，如果不修改
根据书中代码实现
luastack get方法里面获取元素又要判断top范围
func (self *luaStack) get(idx int) luaValue {
	absIdx := self.absIndex(idx)
	if absIdx > 0 && absIdx <= self.top {
		return self.slots[absIdx-1]
	}
	return nil
}
所以不修改top会导致Call调用失败
这里感觉有点矛盾
