### ISSUE TITLE
7.2 LuaTable 第123页代码中的put函数内delete(self._map,key)是否是多余的？

### ISSUE THREAD

**Issue by ShakeM** [zxh0/luago-book#27]
```
	if idx, ok := key.(int64); ok && idx >= 1 {
		arrLen := int64(len(self.arr))
		if idx <= arrLen {
			self.arr[idx-1] = val
			if idx == arrLen && val == nil {
				self._shrinkArray()
			}
			return
		}
		if idx == arrLen+1 {
			delete(self._map, key) //此处的delete
			if val != nil {
				self.arr = append(self.arr, val)
				self._expandArray()
			}
			return
		}
	}
```
一直没想明白这里delete(self._map, key)的用途是什么。感觉不管什么情况下，都不会真正触发delete。

当插入Table的键是“len(数组)+1”后，那么数组会自动重整（expand），map键“len(数组)+1”的值应该一直是空，后续操作应该不会触发delete。

例如：
1. Table状态为：数组 [1,2,3,4] 字典 {6:6,8:8}
2. 设置t[5]=5后，此时不会真正触发delete，会自动expand成状态：数组[1,2,3,4,5,6] 字典{8:8}
3. 此时，字典len(数组)+1键为空，之后的操作也不会真正触发delete

只有当状态为：数组[1,2,3,4]，字典{5:100,6:6,8,8}时。
此时，插入t[5]=5，才会真正触发delete。但我实在想不到，在什么情况下，会出现上述情况，即在字典中存在键“len(数组)+1”。

望解答，谢谢。

**Comment by zxh0** [comment]
可能当时这样考虑的，比如：
1. Table状态为：数组 [1,2,3,4] 字典 {6:6,8:8}
2. 设置t[5]=nil

**Comment by zxh0** [comment]
你好，我也仔细看了一下，好像这个delete语句的确是有些多余😅
