### ISSUE TITLE
x64-based PC 的 size_t 为 4 bytes

### ISSUE THREAD

**Issue by yjhmelody** [zxh0/luago-book#3]
请问这个处理？

**Comment by zxh0** [comment]
把binary_chunk.go里面的CSIZET_SIZE改为4就可以了。

**Comment by yjhmelody** [comment]
@zxh0  嗯 这个我知道，我想请问下，对后面的实现有无影响？

**Comment by zxh0** [comment]
没有影响，不过因为代码是按章组织的，增量的，所以每一章都需要改一下

**Comment by yjhmelody** [comment]
OK! 谢谢

**Comment by zxh0** [comment]
不客气。也可以加入本书的QQ群，这样后面交流起来比较方便。
